test example in README

diff --git a/.github/workflows/ci_nix.yml b/.github/workflows/ci_nix.yml
--- a/.github/workflows/ci_nix.yml
+++ b/.github/workflows/ci_nix.yml
@@ -22,7 +22,22 @@ jobs:
       - uses: cachix/install-nix-action@v23
         with:
           nix_path: nixpkgs=channel:nixos-unstable
-
-      #  the result folder is produced by the previous step
+          
       - name: Run all tests
         run: nix develop -c sh -c 'export ROC=roc && export EXAMPLES_DIR=./examples/ && ./ci/all_tests.sh'
+
+      - name: build example in README.md
+        run: |
+          roc_block_count=$(grep -c '```roc' README.md)
+          
+          # Error if more than one Roc code block
+          if [ $roc_block_count -gt 1 ]; then
+            echo "Error: Found $roc_block_count Roc code blocks in README.md. I only know how to test one. Modify this CI step to test them all."
+            exit 1
+          fi
+
+          # Extract roc code block from README.md
+          sed -n '/```roc/,/```/p' README.md | sed '1d;$d' > readme.roc
+
+          # Build the code to make sure it works
+          roc build readme.roc --linker=legacy
